[project]
name = "decision-tree"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.18.4",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "pyzmq>=27.1.0",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
]
